name: "Move Issue to Awaiting Response"

on:
  issue_comment:
    types: [created]

jobs:
  move-to-awaiting:
    runs-on: ubuntu-latest
    # Only run on actual issues, not PRs
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Get GitHub App Token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.YOUR_APP_ID }}
          private-key: ${{ secrets.YOUR_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          
      - name: Move Issue to Awaiting Response
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.token.outputs.token || github.token }}
          script: |
            // Your script to move the issue to "awaiting response"
            // This will depend on whether you're using Projects (classic) or Projects (beta)
