name: nahuj

on:
  issue_comment:
    types: [created]

jobs:
  move_to_awaiting_response:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null  # only run on issues, not PRs
    steps:
      - name: Move issue to “Awaiting Response”
        uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_url: https://github.com/users/Ftwas/projects/7
          column_name: "Awaiting Response"
          # Filter for the just-commented issue by its number
          issue_query: "number = ${{ github.event.issue.number }}"
