name: Move Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "Awaiting Response" column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "Your Project Name"
          column: "Awaiting Response"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
