name: Move Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  move-to-awaiting-response:
    runs-on: ubuntu-latest
    name: Move Issue to Awaiting Response
    steps:
      - name: Move issue to Awaiting Response column
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "@Ftwas's trilili"
          column: "Awaiting Response"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
