name: "Change Issue Status After Comment"

on:
  issue_comment:
    types: [created]

jobs:
  change-status:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == false # Tikrinama, ar tai issue, o ne PR
    steps:
      - name: Move issue to new status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Gauti issue numerį
            const issueNumber = context.issue.number;
            
            // Pridėti naują etiketę (label), kuri atspindi naują statusą
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: ['awaiting-response']
            });
            
            // Pašalinti seną statuso etiketę, jei tokia yra
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                name: 'in-progress'
              });
            } catch (error) {
              console.log("Sena etiketė neegzistuoja arba nepavyko pašalinti");
            }
            
            // Pridėti komentarą apie statuso pakeitimą
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: 'Šio issue statusas buvo pakeistas į "Awaiting Response".'
            });
