name: Move issues to Awaiting Response

on:
  issue_comment:
    types: [created]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Move issue to 'Awaiting Response' column
      uses: fojia/action-move-issues-to-column@master
      with:
        project: 'Ftwas's trilili'
        column: 'Awaiting Response'
        owner: 'Ftwas'
        repo: 'spirntaslialia'
        github_token: ${{ secrets.GITHUB_TOKEN }}
